<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fm</string>
		<string>fmc</string>
	</array>
	<key>name</key>
	<string>Fewest Moves</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(?i)niss\b</string>
			<key>name</key>
			<string>keyword.control.fm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([URFDLB]w?[''2]?|[xyz][''2]?)</string>
			<key>name</key>
			<string>notation.fm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[[rufdlb][''2]?\]</string>
			<key>name</key>
			<string>notation.fm</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//|#</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.fm</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.fm</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fm</string>
	<key>uuid</key>
	<string>56a09a3f-3e4b-4fc4-ae9a-d81df056a9ec</string>
</dict>
</plist>
